# ─────────────────────────────────────
# Netlify config – Edge Functions only
# ─────────────────────────────────────
[build]
  command = "echo 'skip site build'"
  publish = "."

[functions]
  node_bundler          = "esbuild"
  external_node_modules = ["https-proxy-agent"]   # ← moved here

[[edge_functions]]
  function = "data"
  path     = "/data"
  cache    = "manual"

[[edge_functions]]
  function = "data"
  path     = "/data.json"
  cache    = "manual"

[[edge_functions]]
  function = "data-page"
  path     = "/data.html"
  cache    = "manual"
