[build]
  command = "echo 'skip site build'"
  publish = "."

[functions]
  node_bundler = "esbuild"

[[edge_functions]]
  function = "data"
  path     = "/data"
  cache    = "manual"
  external_node_modules = ["https-proxy-agent"]   # ← NEW

[[edge_functions]]
  function = "data"
  path     = "/data.json"
  cache    = "manual"
  external_node_modules = ["https-proxy-agent"]   # ← NEW

[[edge_functions]]
  function = "data-page"
  path     = "/data.html"
  cache    = "manual"
