name: telegram-alert

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install (no deps)
        run: npm install
      - name: Run alert
        run: npm run alert
